// 语气包只控制用户可见文案；事件类型、角色和状态字段仍使用稳定的内部值。
const GENTLE_V1 = {
  id: "gentle_v1",
  name: "温柔",
  version: 1,
  schemaVersion: 1,
  // 用户可见的核心产品词汇。内部事件类型和状态值保持不变。
  vocabulary: {
    promise: "约定",
    card: "心意卡",
    score: "心意分",
    traces: "印记",
    memories: "拾光之旅",
    diary: "随手记",
    mood: "心情",
    anniversary: "纪念日",
    ledger: "心意分",
  },
  shared: {
    begin: "你们的故事开始了",
    beginContent: "你们的故事，从这一天开始",
    journal: "随手记",
    mood: "心情",
    promise: "约定",
    card: "心意卡",
    cardExecute: "卡片约定",
    accept: "答应了",
    pause: "先放一放",
    cancel: "先放下了",
    backup: "拾光备份",
  },
  eventLabels: {
    begin: "你们的故事开始了",
    initiate: "许下了约定",
    counter: "再商量了一下",
    accept: "答应了",
    submit: "做好了",
    confirm: "收下了",
    revise: "TA 想再改改",
    cancel: "先放下了",
    pause: "先放一放",
    journal: "随手记",
    mood: "心情",
    anniversaryGrant: "纪念日心意",
    festivalGrant: "节日心意",
    remember: "先记着",
    create: "准备了",
    request: "发起了",
  },
  actions: {
    promise: {
      initiate: "修改约定",
      counter: "再商量一下",
      accept: "嗯，就这样",
      submit: "做好啦，提交",
      confirm: "就这样，很好",
      revise: "再试一次",
      cancel: "取消这条约定",
      pause: "暂不执行",
    },
    card: {
      offer: "提议这份心意",
      accept: "按这个分来",
      counter: "再商量一下",
      pause: "暂不启用",
      withdraw: "这张卡先不发了",
      giveup: "这张卡先放着吧",
      redeem: "使用心意卡",
    },
  },
  cards: {
    pageTitle: "我的心意卡",
    customGuideEntry: "送 TA 定制心意卡",
    customRespondEntry: "向 TA 定制心意卡",
    customGuideSubtitle: "写下我愿意为 TA 做的事情，等TA用心意分兑换出来。",
    customRespondSubtitle: "写下你想收到的心意，TA 确认后，你可以用心意分兑换。",
    customSave: "保存到卡册",
    customRequest: "发给 TA 确认",
    cardLocked: "已锁定 {score} 分 · 以后可以随时唤起这个小心意",
    paused: "TA 想了想，这张卡先不启用。不是你不好，是这件事 TA 现在还没准备好。卡还在，改天想要了，随时可以再拿出来。",
    inputTitle: "这张卡，值多少心意分？",
    cancel: "取消",
    send: "发送给对方",
    customNamePlaceholder: "心意卡名称",
    customGuideDescPlaceholder: "写下这份心意想认真完成的事",
    customRespondDescPlaceholder: "我希望 TA 为我做的事情",
    scorePlaceholder: "奖励分值（1-50）",
    payScorePlaceholder: "愿意为这份心意支付多少分（1-50）",
    missing: "写下名称、说明和分值",
    scoreRange: "分值请填 1-50",
    retry: "没成功，别急，再试一次",
    saved: "已放进卡册",
    sent: "已发给 TA",
    fillScore: "想好了再填",
    accept: "接受这份心意",
    resume: "重新启用",
    resend: "重新发给 TA",
    giveup: "放弃这张卡",
  },
  presetCards: [
    { name: "写给你的信", desc: "邀请对方为你写一封专属信件。信里可以是被看见的细节、真诚的认可、想说的话，或想一起抵达的未来；它将成为只属于你们的珍藏。" },
    { name: "你的时间归我", desc: "一起预留不少于 30 分钟的专属陪伴时间。暂时放下分心的事，把注意力留给彼此；当天想做什么，可以提前沟通，也可以留一点惊喜。" },
    { name: "只这样叫你", desc: "邀请对方为你想一个只属于彼此的新称呼，并分享它背后的含义。它可以留在日常里，也可以随着你们的故事慢慢生长。" },
    { name: "我记得那一天", desc: "挑选一段共同经历，邀请对方用自己的视角把它认真写下来：发生了什么、记住了哪些细节，以及为什么值得被珍藏。" },
    { name: "我们的小仪式", desc: "一起创造一个只属于两个人的小仪式：一句固定的话、一次见面的小流程，或一个有纪念意义的默契。让它在日常里慢慢成为你们的记号。" },
    { name: "我眼里的你", desc: "邀请对方记录最近一段时间里看见的你：闪光点、变化、努力和期待。每一次更新，都是重新认识彼此的机会。" },
    { name: "我们拉勾勾", desc: "为你们的相处写下一条新的小约定，可以关于交流、陪伴或生活习惯。把双方认可的默契，变成可以一起遵守的开始。" },
  ],
  memories: {
    title: "拾光之旅",
    subtitle: "聚散终有时，让回忆有处可栖。",
    backupTitle: "备份旧时光",
    restoreTitle: "重逢旧时光",
    export: "📋 一键生成并复制备份码",
    import: "📥 读取剪贴板并识别",
    disbandTitle: "要走了吗",
    disbandConfirm: "确认解除空间",
    backupOnly: "空间已经解除，这里只读保留你们共同走过的记录。你可以导出备份，也可以提前删除；不会自动恢复关系。",
    backupExport: "导出这份备份",
    backupDelete: "提前删除备份",
    backupImport: "读取剪贴板并识别",
    restoreSteps: "从微信收藏取回之前的备份，让故事继续。",
    disbandText: "解除后，你会立即退出当前空间。另一方仍可在保留期内查看和导出这段记录。",
    spaceNamePlaceholder: "请输入空间名确认",
    confirmDisband: "确认解除空间",
    stay: "先留下",
    backupUntil: "备份保留至：",
    backupSteps: ["1. 点击下方按钮，自动复制备份码", "2. 打开微信「我」→「收藏」右上角新增笔记", "3. 长按粘贴并保存（建议备注：拾光备份）"],
    restoreStepsList: ["1. 在微信收藏打开之前的备份笔记", "2. 长按全选复制内容", "3. 回到这里，点击下方按钮自动识别"],
    stepTitle: "操作步骤",
    backupStep1: "1. 点击下方按钮，自动复制备份码", backupStep2: "2. 打开微信「我」→「收藏」右上角新增笔记", backupStep3: "3. 长按粘贴并保存（建议备注：拾光备份）",
    restoreStep1: "1. 在微信收藏打开之前的备份笔记", restoreStep2: "2. 长按全选复制内容", restoreStep3: "3. 回到这里，点击下方按钮自动识别",
    manualHint: "未检测到有效备份。若备份码较长，可长按粘贴到下方：",
    manualPlaceholder: "粘贴备份码内容",
    parse: "解析备份内容",
    found: "找到备份数据",
    space: "空间：",
    size: "备份大小：",
    records: "记录：",
    mergePreview: "将合并到当前空间，已有记录会保留并自动去重",
    restorePreview: "将根据备份重新建立这个空间",
    confirmImport: "确认导入",
    confirmRestore: "确认恢复",
    cancelRestore: "先不恢复",
    clipboardTitle: "为什么用剪贴板",
    clipboardText: "微信小程序限制，无法直接导出文件。但通过微信收藏保存，换了手机也能找回。",
    backupGenerateTitle: "生成备份码",
    backupGenerateText: "备份包含你们的约定、日记、心意和纪念日记录，已压缩为 {sizeKB} KB。复制到剪贴板后，请只粘贴到微信收藏等可信位置。",
    copy: "一键复制",
    noCopy: "先不复制",
    copied: "备份码已复制",
    noBackup: "未检测到有效备份，可手动粘贴",
    readFail: "读取失败，请重试",
    finalConfirm: "最后确认",
    disbandConfirmText: "解除后，你会立即退出这个空间，也可以马上重新结对。为避免另一方失去共同记录，系统会为 TA 保留 7 天只读备份；期间 TA 可以查看、导出或提前删除。确定解除吗？",
    deleteTitle: "删除这份备份",
    deleteText: "删除后，这段记录将无法再查看或导出。确定删除吗？",
    confirmDelete: "确认删除",
    noDelete: "先不删除",
    deleted: "备份已删除",
    invalid: "备份数据无效，请检查是否完整",
    recovered: "你们的故事回来了",
    restoreFail: "恢复失败，请重试",
    disbandReadonlyTitle: "这段记录暂时为你保留",
    copyPackPreviewPrefix: "语气：",
    copyPackOverwrite: "将覆盖当前本机语气，不改变空间数据。",
    importConfirm: "确认导入",
    copyPreviewVocabulary: "核心词汇：",
    copyPreviewHome: "首页示例：",
    copyPreviewAction: "按钮示例：",
  },
  promise: {
    title: "新建小约定",
    subtitle: "赋予这件事一点意义，看着 TA，在你的期待里完成",
    titleLabel: "约定标题",
    scoreLabel: "心意分",
    submit: "发出这个小约定",
    scoreRange: "心意分在 0-50 之间，重新填一下",
  },
  diary: {
    title: "今天的日记",
    placeholder: "此刻，想对 TA 说一句什么？",
    submit: "记一笔此刻",
  },
  traces: {
    title: "印记",
    subtitle: "这里的每一条，都是我们走过的",
    all: "全部",
    empty: "这里还空着，去留下第一条印记吧",
    emptyTitle: "这里还没有故事",
    emptyText: "去留下第一条印记吧",
    emptyStartedTitle: "故事已经开始了",
    emptyStartedText: "等下一笔印记留下来",
    emptyFilterTitle: "这里暂时没有这类印记",
    emptyFilterText: "换一个筛选看看",
    anniversaryCategory: "纪念日",
    promiseFilter: "约定",
    cardFilter: "心意卡",
    replyMoodPrefix: "TA 当时的心情：",
    systemActor: "系统",
    customCardCreateLabel: "为 TA 准备了",
    customCardRequestLabel: "向 TA 提出了",
    storyStartCategory: "故事开始",
    storyStartTitle: "你们的故事开始了",
    journalTitle: "留下一笔随手记",
    moodReplyTitle: "回应 TA 的心情",
    cancelContent: "这条约定，先放下了。没能一起完成，但你们的每一次商量，都算数。",
    rememberedContent: "这一天，被记着了",
    beginContent: "你们的故事，从这一天开始",
    cardExecuteCategorySuffix: "执行",
    festivalCategory: "节日",
  },
  detail: {
    score: "心意分",
    inputPlaceholder: "想对 TA 说一句什么？（选填）",
    promiseTitle: "约定标题",
    scoreLabel: "心意分",
    reviseReason: "修改理由（选填）",
    confirmEdit: "确认修改",
    cancelEdit: "取消",
    locked: "已锁定 {score} 分 · 以后可以随时唤起这个小心意",
    executeSubmit: "答应了，正在为你做这件事",
    executePause: "今天先不做这张卡片的约定。不是不答应，是想等更好的时候。卡还在。",
    executeConfirm: "收到了，很满足",
    executeRevise: "希望更好，再试一次也愿意等",
    executeCancel: "这张卡的约定，先放下了",
    promiseCancel: "这条约定，先放下了。没能一起完成，但你们的每一次商量，都算数。",
    remembered: "这一天，被记着了",
    redeem: "使用心意卡",
    used: "已经用上了",
    reasonRequired: "先写一下理由",
    retry: "没成功，别急，再试一次",
    fill: "想好了再填",
    softTwice: "两次都认真报过了，你已经表达得很清楚。接下来，交给 TA 决定。要记得：TA 若先不启用，不是不喜欢你，只是这张卡让 TA 做的事，TA 暂时有点为难。这不是你的问题，别怪到自己头上。",
    softPaused: "TA 想了想，这张卡先不启用。不是你不好，是这件事 TA 现在还没准备好。卡还在，改天想要了，随时可以再拿出来。",
    softEnded: "你已经试了三次，每一次都很用心。这一次先放下吧——不是你不够好，只是这件事，先慢慢来。",
    softCounterEnded: "这几轮商量，你们都认真说了自己的想法，这本身就很好。只是这次，没能谈到一起。接下来，TA 会把这条约定先放下——不是谁错了，只是这件事，先不勉强。",
    eventsTitle: "这个约定的经过",
    collapse: "收起 ⌃",
    expand: "展开 ›",
    scoreRange: "心意分",
    titleSuffix: "标题",
    reasonOptional: "理由（选填）",
    scoreNew: "新的分值",
    way: "文字约定",
  },
  anniversary: {
    title: "纪念日", yearly: "每年", monthly: "每月", delete: "删除", empty: "还没记下特别的日子。你们第一次见面的那天，就很值得记住。", add: "添加纪念日", nameLabel: "纪念日的名字", namePlaceholder: "例如：相识纪念日", dateLabel: "最初的日期", chooseDate: "选择日期", cycleLabel: "提醒周期", save: "保存纪念日", elapsed: "已经一起走了 {days} 天", next: "还有 {days} 天", fill: "想好了再填", retry: "没成功，别急，再试一次"
  },
  ledger: { title: "心意分", subtitle: "每一次答应，都算数。心意，一点一点攒起来", empty: "还没有积攒下心意分哦。完成约定，就会慢慢攒起来", grant: "发放", anniversary: "纪念日心意", festival: "节日心意", redeem: "兑换扣除", refund: "兑换退回" },
  profileHero: { text: "记录每一天的约定、心意和日记，\n让两个人之间的温柔有迹可循。\n\n每一次版本更新，都是我们成长的模样；\n这里记着开始，也藏着归途。\n\n—— 一个人开发的温柔小事", slogan: "始于初见，止于终老" },
  home: {
    newPromise: "新建约定",
    myCards: "我的心意卡",
    todayTitle: "有新的回音",
    recentTitle: "最近的小事",
    todayMood: "今天的心情",
    todayJournal: "今天的随手记",
    waitingReply: "TA 在等你回话",
    firstAnniversary: "记下第一个纪念日",
    firstPromiseGuide: "留下第一个小约定",
    firstPromiseRespond: "等 TA 发起第一个小约定",
    anniversaryGrant: "送 TA 52 分心意",
    inviteTitle: "喊 TA 进来",
    inviteDesc: "空间搭好了，现在喊 TA 进来，两个人的故事才算真正开始。",
    inviteReset: "放弃邀请，重新开始",
    onboardingKicker: "配对完成",
    onboardingSkip: "先看看",
    onboardingNext: "下一步",
    onboardingStart: "开始记录",
    journalEmpty: "今天还没有日记",
    moodInput: "输入你的心情",
    moodPlaceholder: "写入你的心情（≤10字）",
    confirm: "确认",
    cancel: "取消",
    summaryPromise: "小事",
    summaryCard: "心意",
    summaryDiary: "随记",
    summaryDays: "日子",
  },
  profile: {
    title: "我们",
    guideScore: "TA 的心意分",
    respondScoreSuffix: "分 · 爱的积蓄",
    anniversary: "纪念日",
    anniversarySubtitle: "你们的重要日子",
    guideCards: "TA 的心意卡",
    guideCardsSubtitle: "给 TA 的奖励，等 TA 来领取",
    memories: "拾光之旅",
    memoriesSubtitle: "收好我们的故事，重逢时再一起打开",
    theme: "主题",
    copyPack: "显示语气",
    copyPackSubtitle: "只在本机生效",
    disbandIntro: "人海茫茫，两个人能相遇相知，本身就是很深的缘分。不管此刻正在经历什么，那些一起走过的日子、写下的约定、记录的心意，都不该被轻易抹去。建议先去「拾光之旅」，把故事好好收起来。哪怕最终走散，至少那些温柔还有迹可循。",
    themeChoose: "选择一套主题",
    themeDesc: "色彩会同步到当前页面",
    selected: "已选中",
    choose: "点击选择",
    copyChoose: "选择一种表达方式",
    copyUsed: "已使用",
    copyUse: "点击使用",
    localOnly: "只在本机生效",
    restoreGentle: "恢复温柔",
  },
  pair: {
    title: "开始你们的空间",
    guideTab: "引导方",
    respondTab: "回应方",
    joinConfirm: "点确认，就正式在一起了",
    create: "开启属于我们的空间",
    startDateLabel: "我们开始的时间",
    startToday: "就从今天重新出发",
    startEarlier: "我们早就在一起了",
    chooseDate: "选择日期",
    waitingTitle: "空间正在布置中",
    waitingDesc: "命名、称呼、开始的日子，TA 都在为你准备好。",
    waitingInvite: "等 TA 把邀请发来，点开就正式在一起了。",
  },
  errors: {
    backupInvalid: "备份码无效",
    backupNotMatch: "备份码不属于这个空间",
    backupReadOnly: "空间已解除，仅可查看和导出",
    retry: "没成功，别急，再试一次",
    fill: "想好了再填",
    networkRetry: "网络不稳，已保留刚才的内容",
  },
  pairForm: { spaceLabel: "空间名称", spacePlaceholder: "例如：我和你的空间", guideLabel: "引导方的称呼", respondLabel: "回应方的称呼", placeholder: "想好了再填", hint: "称呼一旦确认不再修改，想好了再填" },
};

const CALM_V1 = {
  ...GENTLE_V1,
  id: "calm_v1",
  name: "冷静",
  version: 1,
  schemaVersion: 1,
  vocabulary: {
    promise: "任务",
    card: "奖励卡",
    score: "奖励分",
    traces: "记录",
    memories: "空间备份",
    diary: "日志",
    mood: "今日状态",
    anniversary: "重要日期",
    ledger: "奖励分",
  },
  shared: {
    ...GENTLE_V1.shared,
    begin: "空间已开始使用",
    beginContent: "空间从这一天开始记录",
    journal: "日志",
    mood: "今日状态",
    promise: "任务",
    card: "奖励卡",
    cardExecute: "奖励执行",
    accept: "已确认",
    pause: "暂缓",
    cancel: "已取消",
    backup: "空间备份",
  },
  eventLabels: {
    ...GENTLE_V1.eventLabels,
    begin: "空间已开始使用",
    initiate: "发布了任务",
    counter: "修改了任务条件",
    accept: "已确认",
    submit: "已提交",
    confirm: "已确认完成",
    revise: "要求重新提交",
    cancel: "已取消",
    pause: "已暂缓",
    journal: "日志",
    mood: "今日状态",
    anniversaryGrant: "日期奖励",
    festivalGrant: "节日奖励",
    remember: "已记录",
    create: "创建了奖励",
    request: "提交了申请",
  },
  actions: {
    promise: {
      initiate: "修改任务",
      counter: "修改任务条件",
      accept: "确认任务",
      submit: "提交完成",
      confirm: "确认完成",
      revise: "要求重新提交",
      cancel: "取消任务",
      pause: "暂缓任务",
    },
    card: {
      offer: "提交奖励申请",
      accept: "确认奖励分",
      counter: "修改奖励分",
      pause: "暂不启用",
      withdraw: "撤回申请",
      giveup: "放弃奖励",
      redeem: "兑换奖励",
    },
  },
  cards: {
    ...GENTLE_V1.cards,
    pageTitle: "奖励卡",
    customGuideEntry: "创建定制奖励卡",
    customRespondEntry: "提议定制奖励卡",
    customGuideSubtitle: "写下愿意完成的事项，并设置兑换分值。",
    customRespondSubtitle: "写下希望对方提供的奖励，提交后等待确认。",
    customSave: "保存奖励卡",
    customRequest: "提交给 TA",
    cardLocked: "已锁定 {score} 分，可在需要时兑换",
    paused: "该奖励暂未启用，之后仍可重新处理。",
    inputTitle: "设置奖励分值",
    send: "提交给对方",
    missing: "请填写名称、说明和分值",
    scoreRange: "分值范围为 1-50",
    retry: "操作未完成，请重试",
    saved: "奖励卡已保存",
    sent: "已提交给 TA",
    fillScore: "请填写分值",
    accept: "确认奖励",
    resume: "重新启用",
    resend: "重新提交",
    giveup: "放弃奖励",
  },
  memories: {
    ...GENTLE_V1.memories,
    title: "空间备份",
    subtitle: "备份空间记录，便于之后查看或恢复。",
    backupTitle: "备份空间数据",
    restoreTitle: "恢复空间数据",
    export: "生成数据备份码",
    import: "读取备份并识别",
    disbandTitle: "解除空间",
    disbandText: "解除后你会立即退出当前空间，另一方可在保留期内查看和导出备份。",
    backupOnly: "空间已解除。当前仅可查看、导出或删除备份。",
    backupExport: "导出备份",
    backupDelete: "删除备份",
    backupImport: "读取备份并识别",
    restoreSteps: "从微信收藏读取之前保存的空间备份。",
  },
  promise: {
    ...GENTLE_V1.promise,
    title: "新建任务",
    subtitle: "写下任务内容，并设置对应的奖励分。",
    titleLabel: "任务名称",
    scoreLabel: "奖励分",
    submit: "发布任务",
    scoreRange: "奖励分范围为 0-50",
  },
  diary: {
    ...GENTLE_V1.diary,
    title: "今日日志",
    placeholder: "记录今天想留下的内容",
    submit: "保存日志",
  },
  traces: {
    ...GENTLE_V1.traces,
    title: "记录",
    subtitle: "这里记录空间内发生过的事情",
    empty: "暂无记录",
    emptyTitle: "暂无记录",
    emptyText: "留下第一条记录",
    emptyStartedTitle: "记录已经开始",
    emptyStartedText: "等待下一笔记录",
    emptyFilterTitle: "当前筛选暂无记录",
    emptyFilterText: "换个筛选看看",
    promiseFilter: "任务",
    cardFilter: "奖励卡",
  },
  detail: {
    ...GENTLE_V1.detail,
    inputPlaceholder: "填写回应内容（选填）",
    promiseTitle: "任务名称",
    scoreLabel: "奖励分",
    reviseReason: "修改说明（选填）",
    confirmEdit: "确认修改",
    cancelEdit: "取消",
    redeem: "兑换奖励",
    used: "奖励已兑换",
    reasonRequired: "请填写理由",
    retry: "操作未完成，请重试",
    fill: "请填写必要内容",
    eventsTitle: "任务处理记录",
    collapse: "收起",
    expand: "展开",
    promiseCancel: "任务已取消，历史处理记录仍会保留。",
    remembered: "已记录",
  },
  home: {
    ...GENTLE_V1.home,
    newPromise: "新建任务",
    myCards: "奖励卡",
    todayTitle: "有新的进展",
    recentTitle: "进行中的任务",
    todayMood: "今日状态",
    todayJournal: "今日日志",
    waitingReply: "等待处理",
    firstPromiseGuide: "建立第一条任务",
    firstPromiseRespond: "等待 TA 发布第一条任务",
    anniversaryGrant: "发放 52 分奖励",
  },
  profile: {
    ...GENTLE_V1.profile,
    title: "空间信息",
    guideScore: "TA 的奖励分",
    respondScoreSuffix: "分 · 当前余额",
    anniversary: "重要日期",
    anniversarySubtitle: "空间中的重要日期",
    guideCards: "TA 的奖励卡",
    guideCardsSubtitle: "已创建的奖励，等待 TA 兑换",
    memories: "空间备份",
    memoriesSubtitle: "查看、导出或恢复空间记录",
    theme: "显示语气",
    copyPack: "显示语气",
    copyPackSubtitle: "只在本机生效",
  },
  pair: {
    ...GENTLE_V1.pair,
    title: "建立空间",
    joinConfirm: "确认后加入空间",
    create: "创建空间",
  },
};

// 官方内置只保留两套；其他语气只能通过恢复入口导入到本机。
const COPY_PACKS = { gentle_v1: GENTLE_V1, calm_v1: CALM_V1 };

module.exports = { GENTLE_V1, CALM_V1, COPY_PACKS };
